spring:
  datasource:
    url: jdbc:mysql://localhost:3308/shopwoocomrece?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B7
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: chaukiet98@gmail.com
    password: azhnmknwrxxzkqjs
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 3332
